services:
  - type: web
    name: fichow-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: APP_ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: API_PREFIX
        value: /api/v1
      - key: ALLOWED_ORIGINS
        value: "https://tu-front.vercel.app"
      - key: ENABLE_DOCS
        value: "true"
      - key: JWT_COOKIE_SECURE
        value: "true"
      - key: JWT_COOKIE_SAMESITE
        value: "none"
      - key: AUTO_CREATE_DATABASE
        value: "false"
      - key: AUTO_CREATE_TABLES
        value: "true"
      - key: AUTO_SEED_DATA
        value: "true"
